print("+----------------------------------+")
print("|                                  |")
print("|            Corner Store          |")
print("|                                  |")
print("|    2022-03-29         10:24 PM   |")
print("|                                  |")
print("|    Gallons:           10.870     |")
print("|    Price/Gallon:    $ 2.089      |")
print("|                                  |")
print("|    Fuel total:      $ 22.71      |")
print("|                                  |")
print("|                                  |")
print("+----------------------------------+")